export const KoreanStrings =
{
    AppName: "밸런스 아레나",
    AppTagline: "우리 팀의 선택은 어디로 기울까?",
    AppDescription: "우리 팀의 취향을 발견하는 밸런스 게임",
    LobbyEyebrow: "MEETING PLAYGROUND",
    LobbyTitleLineOne: "고민은 짧게,",
    LobbyTitleLineTwo: "선택은 과감하게.",
    LobbyDescription: "이름을 등록하고 차례대로 선택하세요. 마지막에는 우리 팀만의 취향 리포트가 완성됩니다.",
    ParticipantTitle: "오늘의 플레이어",
    ParticipantDescription: "2명부터 8명까지 참가할 수 있어요.",
    ParticipantPlaceholder: "이름 입력",
    AddParticipant: "추가",
    RemoveParticipant: "삭제",
    DuplicateParticipant: "이미 등록된 이름이에요.",
    ParticipantLimit: "참가자는 최대 8명까지 등록할 수 있어요.",
    ParticipantMinimum: "게임을 시작하려면 2명 이상이 필요해요.",
    GamePreviewTitle: "오늘의 아레나",
    QuestionCountLabel: "질문",
    PlayerCountLabel: "플레이어",
    EstimatedTimeLabel: "예상 시간",
    EstimatedTimeValue: "3~5분",
    StartArena: "아레나 시작",
    RoundLabel: "ROUND",
    ExitGame: "게임 나가기",
    CurrentPlayerPrefix: "지금은",
    CurrentPlayerSuffix: "님의 선택",
    PickInstruction: "둘 중 하나를 골라주세요",
    ChoiceALabel: "A",
    ChoiceBLabel: "B",
    Versus: "VS",
    VoteComplete: "선택 완료",
    WaitingVote: "선택 대기",
    RoundResultEyebrow: "ROUND RESULT",
    RoundResultTitle: "선택이 갈렸어요!",
    RoundResultUnanimous: "완벽한 만장일치!",
    VotesUnit: "표",
    NextQuestion: "다음 질문",
    ViewFinalResult: "최종 결과 보기",
    ResultEyebrow: "ARENA COMPLETE",
    ResultTitle: "우리 팀의 취향 리포트",
    ResultDescription: "같은 질문에도 이렇게 다른 선택이 나왔어요.",
    UnanimousLabel: "만장일치",
    CloseMatchLabel: "가장 팽팽한 질문",
    TotalVotesLabel: "총 선택 수",
    NoCloseMatch: "모든 질문이 한쪽으로 기울었어요",
    QuestionBreakdownTitle: "질문별 결과",
    ResultSectionLabel: "RESULT",
    TeamLeansA: "우리 팀은 A에 조금 더 끌려요",
    TeamLeansB: "우리 팀은 B에 조금 더 끌려요",
    TeamBalanced: "우리 팀은 완벽한 밸런스형이에요",
    ReplaySamePlayers: "같은 멤버로 다시 하기",
    StartNewGame: "새 게임 만들기",
    SessionMissing: "진행 중인 게임을 찾지 못했어요.",
    ReturnToLobby: "로비로 돌아가기",
    Loading: "아레나 준비 중...",
    ExitConfirmTitle: "게임을 나갈까요?",
    ExitConfirmDescription: "현재 투표 기록은 지워지고 로비로 돌아갑니다.",
    Cancel: "계속하기",
    ConfirmExit: "나가기",
} as const;

export const DefaultParticipantNames = ["민준", "서연"] as const;

export const DefaultBalanceQuestions =
[
    {
        Id: "work-style",
        Prompt: "더 집중이 잘 되는 근무 방식은?",
        ChoiceA: "집에서 편안하게 재택근무",
        ChoiceB: "동료와 함께 사무실 출근",
        EmojiA: "🏠",
        EmojiB: "🏢",
    },
    {
        Id: "super-power",
        Prompt: "하나의 초능력만 가질 수 있다면?",
        ChoiceA: "어디든 바로 순간이동",
        ChoiceB: "원할 때 시간을 정지",
        EmojiA: "⚡",
        EmojiB: "⏸️",
    },
    {
        Id: "season",
        Prompt: "평생 한 계절만 살아야 한다면?",
        ChoiceA: "햇살 가득한 여름",
        ChoiceB: "눈 내리는 겨울",
        EmojiA: "☀️",
        EmojiB: "❄️",
    },
    {
        Id: "food",
        Prompt: "평생 하나를 포기해야 한다면?",
        ChoiceA: "커피 없이 살기",
        ChoiceB: "야식 없이 살기",
        EmojiA: "☕",
        EmojiB: "🍕",
    },
    {
        Id: "travel",
        Prompt: "지금 당장 떠날 수 있다면?",
        ChoiceA: "계획 없이 즉흥 여행",
        ChoiceB: "분 단위 완벽한 계획 여행",
        EmojiA: "🎒",
        EmojiB: "🗺️",
    },
    {
        Id: "communication",
        Prompt: "업무 소통 방식 하나만 고른다면?",
        ChoiceA: "빠르게 10분 화상회의",
        ChoiceB: "깔끔하게 정리된 메시지",
        EmojiA: "🎥",
        EmojiB: "💬",
    },
    {
        Id: "reward",
        Prompt: "깜짝 보상으로 더 좋은 것은?",
        ChoiceA: "금요일 오후 즉시 퇴근",
        ChoiceB: "월요일 오전 늦게 출근",
        EmojiA: "🏃",
        EmojiB: "😴",
    },
] as const;
